### ISSUE TITLE
Create a browser app that connects to my outline server

### ISSUE THREAD

**Issue by konstantin-mohin** [Jigsaw-Code/outline-client#1348]
Hi, 

it's a general question, I wanna create a browser app which behind the scene or by pressing a button connects to outline server.

I saw a cordova-plugin in the repo, is this plugin for app development ? 
I wanna have a mobile app for both platforms with custom ui elements.

**Comment by bemasc** [comment]
I'm not sure what you mean by "browser app".  An ordinary web app does not have the ability to reconfigure the device's VPN settings.

The Outline Client is implemented using a webview for the UI, which is implemented using WebComponents.  On Android, iOS, and macOS, the Cordova framework and system webview are used.  On Windows and Linux, the client is implemented using Electron.

This is all open source, so you're free to fork this repo and alter the UI in your fork.

Does this answer your question?

**Comment by konstantin-mohin** [comment]
@bemasc thank you Benjamin,

I meant mobile application that uses a webview for rendering pages (so it'll be like a simple browser) and with possibility to connect to specific outline server.

I found no API of how to connect\disconnect.... to an outline server as well as permissions (like Info.plist configurations), 
so I wonder is this something I can start working with ?

**Comment by bemasc** [comment]
It sounds like you want to make a web browser app that accesses the internet through an Outline server.  This is a nice idea!  Unfortunately, I don't think it's likely to be easily accomplished with the Outline Client codebase, which is designed for setting up a system-wide VPN.

To implement an app of this kind, I recommend starting with a Shadowsocks implementation that exposes a SOCKS5 proxy running on localhost, instead of a VPN-focused implementation like the Outline Client.  Then you can configure your webview to use this SOCKS5 proxy.

Outline servers implement the standard Shadowsocks protocol, so most Shadowsocks client implementations should be able to connect to an Outline server.

**Comment by konstantin-mohin** [comment]
extensive answer,
thank you Benjamin
