### ISSUE TITLE
go-tun2socks connection error

### ISSUE THREAD

**Issue by KilledDebtor** [Jigsaw-Code/outline-client#1449]
Error when i press connect. 

`Outline is starting
loading web app from file:///C:/Program%20Files%20(x86)/Outline/resources/app.asar/www/index_electron.html?appName=Outline
Could not load active tunnel:  [Error: ENOENT: no such file or directory, open 'C:\Users\aleks\AppData\Roaming\Outline\connection_store'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\aleks\\AppData\\Roaming\\Outline\\connection_store'
}
Checking for update
Update for version 1.8.0 is not available (latest version: 1.7.1, downgrade is disallowed).
connecting to 6922b3b3-ac69-4269-8807-d5514ef951d0...
connectivity check failed: Error: Command failed: C:\Program Files (x86)\Outline\resources\app.asar.unpacked\third_party\outline-go-tun2socks\win32\tun2socks.exe -proxyHost 91.197.1.250 -proxyPort 38571 -proxyPassword wySVHEbJGTtr -proxyCipher chacha20-ietf-poly1305 -checkConnectivity

could not connect: f ()
tun2socks stopped with signal: null, code: null.
tun2socks stopped with signal: null, code: null.
disconnected from 6922b3b3-ac69-4269-8807-d5514ef951d0`

**Comment by KilledDebtor** [comment]
Version 1.6.0 working well ...

**Comment by jyyi1** [comment]
This should be related to `outline-go-tun2socks` connection check. The server is reachable (using the old ss-local and tun2socks), but go-tun2sock reports that it is not. The error code is [`4 UDPConnectivity`](https://github.com/Jigsaw-Code/outline-go-tun2socks/blob/158941049c2db3a6b5141fa11d61870ffa8988b4/outline/shadowsocks/connectivity.go#L56), @bemasc can we ignore UDP connection issues during connectivity check?

**Comment by bemasc** [comment]
The client code doesn't ignore UDP connection issues during connectivity check, but it [intercepts them](https://github.com/Jigsaw-Code/outline-client/blob/1785b7adc6305a2e1249aa3dca73c78446279014/src/electron/go_vpn_tunnel.ts#L300) and uses them to adjust the configuration automatically.  If this is failing, it's because the subprocess return code is being lost.

It would help to insert a debug check (or expanded log statement) in the client JS to confirm the exit code that is being observed by `checkConnectivity()` in node.

**Comment by jyyi1** [comment]
Thanks @bemasc , I can take a deep look at the client logic.
