### ISSUE TITLE
build outline server using Docker 

### ISSUE THREAD

**Issue by Shah-devs** [Jigsaw-Code/outline-client#1466]
**Describe the issue**
> Verifying that Docker is installed .......... OK
> Verifying that Docker daemon is running ..... OK
> Setting PUBLIC_HOSTNAME to external IP ...... OK
> Creating persistent state dir ............... OK
> Generating secret key ....................... OK
> Generating TLS certificate .................. OK
> Generating SHA-256 certificate fingerprint .. OK
> Writing config .............................. OK
> Starting Shadowbox .......................... OK
> Starting Watchtower ......................... OK
> Verifying Outline server is healthy ......

stuck here 

**Environment**
 - OS: [Windows 10, WSL 2 Ubuntu distor]
 - NPM version (`npm --8.7.0`)
 - Node.js version 16.14.2.0

**Additional context**

**Comment by Shah-devs** [comment]
hi lads,
any insights on what's wrong here?

**Comment by legiorange** [comment]
You can try Docker desktop for Windows or podman.
May it work .

**Comment by Shah-devs** [comment]
@legiorange thanks lad, but as you see docker is up and running, it stuck on verifying server to be healthy... honestly I gave up, because the problem is so vague and confusing, everything works but it stucks at the last stage.

**Comment by rohanmehra20** [comment]
Thank you for reaching out! If this is still an issue for you, please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
