### ISSUE TITLE
Windows 7: No Internet when Outline Client is connected to the server

### ISSUE THREAD

**Issue by aerpyljov** [Jigsaw-Code/outline-client#1473]
**Describe the bug**
I can browse Internet when Outline Client is disconnected.
Then I connect Outline Client to the server successfully.
After that I cannot open any website, there is no Internet access any more. I can ping my Outline Server only; any other IP-address, even 8.8.8.8, gets timeout error.
When I disconnect Outline Client, the Internet is accessible again.

I also have another computer with Windows 11, smartphone with Android and iPad with iOS - everywhere Outline works fine. With the same Outline server, through the same Wi-Fi network. 

**Additional context**
Earlier Outline worked well at the same computer.
I uninstalled almost everything except Windows 7 itself and deleted my user profile.
In several months as a new user I installed Outline Client again, and this bug appeared.

**Client System:**
 - Outline Client Version: Windows 1.8.1
 - Your Operating System: Windows 7

**Comment by vyacheslavslava** [comment]
The same problem on windows server 2019
<img width="696" alt="image" src="https://user-images.githubusercontent.com/32650052/202819437-c0f1899f-6f20-4cc7-ba5e-8b91cb3a5efa.png">

**Comment by rohanmehra20** [comment]
Thank you for reaching out! If this is still an issue for you, please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.

**Comment by aerpyljov** [comment]
I have already solved this problem by upgrading MS Windows from 7 to 10.
