### ISSUE TITLE
Conncection speed issues Windows client vs Android client

### ISSUE THREAD

**Issue by emryysDE** [Jigsaw-Code/outline-client#1491]
Dear Outline Team,

first of all thanks for your awesome project and work, it helped me immensely in the past weeks!

I have succesfully set up my own Outline Server and it is working fine so far - the only issue I am having is the connection speed on the Windows client.
In Windows, speed doesn't go above 30mbps. However, using the android client on the same network, i get speeds up to 100mbps.
What might cause that disparity? Is it client side or server side?

Any help would be greatly appreciated! 

Cheers,
emryysDE

**Comment by hmffa** [comment]
Can you please let me know what provider are you using? Digitalocean?

**Comment by emryysDE** [comment]
Digitalocean as well as the Google Cloud are unfortunately blocked by my ISP, so I found another provider at De-CIX called Synlinq.
Setup was fine and things are running smoothly, except for the connection speed in Windows.

**Comment by rohanmehra20** [comment]
Thank you for reaching out! If this is still an issue for you, please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
