### ISSUE TITLE
Let’s build a new solution for Iranian users. 

### ISSUE THREAD

**Issue by wyntrson** [Jigsaw-Code/outline-client#1533]
**Describe the bug**
My Iranian friends are unable to connect and they get the “incorrect” key error. 

**To Reproduce**
Try to connect to an outline server from 

**Submit Feedback**
We should come up with a solution to ensure the governments can’t detect and block outline.

**Comment by rohanmehra20** [comment]
Thank you for reaching out! If this is still an issue for you, please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
