### ISSUE TITLE
Outline Servers Are being blocked in Iran since ~5 days ago. 

### ISSUE THREAD

**Issue by PhoenixMMXXIII** [Jigsaw-Code/outline-client#1543]
We have multiple Outline Servers in various locations. We have verified that they are being detected in few hours after users start using them from Iran. Can someone help and share experience? 

The pattern is like this: 
First, they connect and it works. After few hours, the VPN connects to the server, but there is no internet connection

**Comment by LeoYako** [comment]
I am observing the same situation in UAE on PC with Win11: it starts several days ago, connection with my own european outline server is established but Internet connection sometimes works, sometime not: Chrome doesn't work, ping win11 comandlet not, some games not, but Edge is working and mobile phone connected the same wifi network works (so local wifi adjustments doesn't matter)! But newest v1.9.1 it works fine! Try it

**Comment by phoenixVPN** [comment]
@LeoYako 
That issue that you are experiencing usually resolved by re-installing the Outline Client.

**Comment by LeoYako** [comment]
@phoenixVPN thanks, will try

**Comment by rohanmehra20** [comment]
Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
