### ISSUE TITLE
Missing downloads

### ISSUE THREAD

**Issue by 4044ever** [Jigsaw-Code/outline-client#155]
https://getoutline.org has no downlink for the Android client. Only to the playstore - not everybody has access to that, specially in countries you really need it.

Solution:
Add link to APK 

On Github I found a page with planty of Android daily releases - but the latest stable is missing.

https://github.com/Jigsaw-Code/outline-client/releases

Solution:
Add or mark latest stable release.

Current workaround for the brave:
Get whatever is claimed 'latest' from some sort of APK warez sites.

**Comment by alalamav** [comment]
Hi @4044ever, thanks for the feedback. We tag the latest stable releases with their version (i.e. [Android v1.1.1](https://github.com/Jigsaw-Code/outline-client/releases/tag/android-v1.1.1)). Additionally, you can find the Android and Windows clients at [outline-releases](https://github.com/Jigsaw-Code/outline-releases/tree/master/client). The Apple clients must be distributed through the App Store due to the entitlements they require so we do not offer downloads for these.
