### ISSUE TITLE
How to redirect an incoming connection to a different outline server address

### ISSUE THREAD

**Issue by arkh91** [Jigsaw-Code/outline-client#1579]
I have 2 servers, #1 and #2
outline server has been installed on server 2

I need the client to connect to server 1 and traffic to be redirected to server 2.

**Comment by rohanmehra20** [comment]
Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
