### ISSUE TITLE
does not connect to known working servers

### ISSUE THREAD

**Issue by NektoNektovich** [Jigsaw-Code/outline-client#1593]
decided to try the exotic distribution simply linux p10.1 x86_64. The outline client started only with the --no-sandbox switch, but after requesting root access it does not connect to known working servers, to which it connects perfectly in debian 11 :( tried outline clients 1.9 and 1.10

**Comment by AndreyPnm** [comment]
Same bug on latest version for ios. Previously worked keys become invalid. Creating new key doesn't help. App version is 1.10.0

**Comment by rohanmehra20** [comment]
Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
