### ISSUE TITLE
TAP device failed to install with error code 2.

### ISSUE THREAD

**Issue by singhayush20** [Jigsaw-Code/outline-client#1611]
I am trying to install Outline Client on my Windows 11 Dell Laptop. When installing I am getting the following error-
![image](https://user-images.githubusercontent.com/106401615/229219912-af89ae7e-5bc8-4d1c-b053-43ae97b6ae87.png)

After I get this message, the client installs and when I try to connect to a server, I get the error-
![image](https://user-images.githubusercontent.com/106401615/229220358-254dc34c-4db1-4c27-818c-a5b469ded379.png)

I have the following network adapters installed-
![image](https://user-images.githubusercontent.com/106401615/229220077-1a9da608-9aed-4d7c-81f2-892d89905166.png)

**Comment by rohanmehra20** [comment]
Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.

Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
