### ISSUE TITLE
An unexpected error has occurred. Try restarting the process. If this error occurs again, send feedback.

### ISSUE THREAD

**Issue by VasyaRns** [Jigsaw-Code/outline-client#1615]
**Describe the issue**
An unexpected error has occurred. Try restarting the process. If this error occurs again, send feedback.
**Environment**
 - OS: MacOS 13.3.1 
 - NPM version 8.19.3
 - Node.js version v18.13.0

**Additional context**
I used to be able to connect to vpn, but now I can't. Works great on other devices (ios, android, win 10)

**Comment by VasyaRns** [comment]
<img width="338" alt="image" src="https://user-images.githubusercontent.com/104196812/232226262-5e24879c-b817-4255-a7b4-3e14c69a90c8.png">

**Comment by VasyaRns** [comment]
<img width="300" alt="image" src="https://user-images.githubusercontent.com/104196812/232226294-77872547-250b-4b35-9a99-3675d0d65dd0.png">

**Comment by rohanmehra20** [comment]
Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.

Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.

**Comment by rohanmehra20** [comment]
Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
