### ISSUE TITLE
unstable outline client 10 & 11 in Xiaomi Redmi A1+

### ISSUE THREAD

**Issue by shishehgar** [Jigsaw-Code/outline-client#1646]
I did a new installation ( outline client version 10 and 11 on android OS ) on the Xiaomi Redmi A1+ phone, but every few minutes it disconnects and I have to reconnect. OS is android 12 Go.
Mostly this happens when I run programs such as WhatsApp, Telegram or Instagram.
I used v2ray and had no problem.

any one can help me?? please

**Comment by maddyhof** [comment]
Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
