### ISSUE TITLE
Sorry, an unexpected error occurred. Quitting and restarting may help. If this happens again, please submit feedback.

### ISSUE THREAD

**Issue by Remsy2** [Jigsaw-Code/outline-client#1689]
Hi!
Tried all versions, everywhere the same error.
Sorry, an unexpected error occurred. Quitting and restarting may help. If this happens again, please submit feedback.

![Screenshot_44](https://github.com/Jigsaw-Code/outline-client/assets/70918996/dad2fb88-2ddf-436e-9c5c-2ec5edc36af0)
![Screenshot_444](https://github.com/Jigsaw-Code/outline-client/assets/70918996/0477fad8-da64-489c-bc6d-e932636c3707)

Could anyone please help me to solve that issue?

**Comment by maddyhof** [comment]
Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs. Feel free to reply to this issue with the ticket reference number as well.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
