### ISSUE TITLE
Custom domains

### ISSUE THREAD

**Issue by philkunz** [Jigsaw-Code/outline-client#400]
Whats the safest supported way to use a custom remapable domain for a server instead of an IP? Just mapping a domain name and using it doesn't seem to work.

**Comment by trevj** [comment]
@philkunz The client does support invites (`ss://xxx`) with domain names rather than IPs. At some point Outline Manager will have support for this but I'm afraid in the meantime you'll have to manually re-write your ss:// URL to replace the IP with a hostname.

Did you already try this? If not, did the invite work for you?

**Comment by philkunz** [comment]
Yeah it is working fine with rewriting the connection Urls. Since we use 1password to get stuff around to people I can just edit them in 1Password before sharing. Btw. are there any plans for a documented and exposed outline server API, that outline manager uses? It would make it much easier to integrate outline into LDAP systems and also to do stuff like IP replacement on the fly.

**Comment by trevj** [comment]
@philkunz OK sounds like the original issue is resolved - great.

Regarding an API, we do plan to eventually document the API but I'm afraid all that's available right now is this very short guide - but I hope it helps:
https://github.com/Jigsaw-Code/outline-server/tree/master/src/shadowbox#access-keys-management-api
