### ISSUE TITLE
Add Brew cask install

### ISSUE THREAD

**Issue by guoyida** [Jigsaw-Code/outline-client#437]
I noticed that I could install outline-manager through brew cask, but not for outline-client. 

Could you please add outline-client to the repository?

Thanks

**Comment by trevj** [comment]
@guoyida Thanks for trying Outline. I hadn't realised we were in Homebrew - great! Regarding the client, I'm afraid that because it uses VPN it *must* be distributed via the Apple Store. Sorry :-/

@alalamav Correct me if I'm wrong.

**Comment by insyria** [comment]
Hello @trevj , 

I don't think that VPN _must be _ distributed via the Apple Store.
The clients for [StrongVPN](https://strongvpn.com/vpn-apps/mac/), [Freedome](https://www.f-secure.com/en/home/products/freedome) can be downloaded as .pkg or .dmg and then installed.

This would be really helpful in automation !

**Comment by alalamav** [comment]
Hi @insyria, the Outline clients rely on the NetworkExtension framework to establish a full-system VPN. In order to receive the entitlements to user the NetworkExtension framework, the app must be distributed through the App Store (see [this post](https://forums.developer.apple.com/thread/67613) for more information). 
The apps you mention likely do not use the NetworkExtension framework, but instead rely on default protocols such as IPSec or L2TP.

**Comment by artk42** [comment]
@insyria @guoyida Mac appstore (mas) provides somehow even more convenience to follow stricter security model of distribution, as if you use [mas-cli](https://github.com/mas-cli/mas) as an extension to brew to control packages.
However, the update cycle is slower in MAS
