### ISSUE TITLE
can not connect on windows 10

### ISSUE THREAD

**Issue by galenzhao** [Jigsaw-Code/outline-client#520]
$ yarn do src/electron/run
....
Outline is starting
Pipe connected
Got data from pipe for action: resetRouting
could not connect: Error (spawn UNKNOWN)

git clone from master, the code works well on iOS and android.

**Comment by trevj** [comment]
@galenzhao Apologies for the slow reply.

I'm afraid for Windows the background service must be running - the client should have prompted you for admin privileges so that it could install the service. Did this happen?

Regardless, if you first install the client the regular way (download from getoutline.org) before running with `yarn do` then the service should be found.
