### ISSUE TITLE
Compatibility issues with Aquantia Ethernet controller

### ISSUE THREAD

**Issue by penderkori** [Jigsaw-Code/outline-client#527]
Hello!
I have a compatibility issue with my Aquantia Ethernet controller
I use a dual LAN system and use both the Aquantia AQC108 chipset and the Intel I211.
When I try to connect to use the Outline client, I get the message "Another VPN is active". I have deleted another VPN client but still see this message.
However, I disabled my Aquantia and confirmed that it was well connected.
There seems to be a compatibility issue with the Aquantia Ethernet controller :(
I am using Windows 10 and it is release 1809
It works well on my other devices. (iOS)

**Comment by trevj** [comment]
@penderkori Thanks for using Outline. Many thanks for the report, this is very interesting. We haven't tested dual LAN systems on Windows. The reason it fails with this message is because when we tested Outline with other VPNs active, multiple network interfaces on the system would have gateways - of course, it's the same situation with dual (or more) LAN systems.

This is very similar to this issue which I recently re-opened:
https://github.com/Jigsaw-Code/outline-client/issues/262

Given this, I'm going to try to prioritise a fix or workaround here.

**Comment by penderkori** [comment]
@trevj 
I think so too.
V1.2.27
The same problem occurred on another PC with Intel Ethernet and Realtek Ethernet cards 
Maybe multiple network interfaces or gateways are affecting
If disable the other network interface and then try to connect to the VPN and then enable the interface again, there is no problem with using it.
I hope this information will help

And Thank you for quick response :)

**Comment by trevj** [comment]
@penderkori You're welcome. What you say makes sense to me: currently Outline does not try to identify which default gateway is the "main" gateway. What I think might work, though, is to pick the gateway on the network device having the lowest interface metric. I will experiment with this and get back to you.

**Comment by trevj** [comment]
@penderkori I just released Windows client 1.2.29 which should help with this issue. If you still run into problems after updating please re-open. Again, many thanks for the useful bug report!
