### ISSUE TITLE
iOS Build Error

### ISSUE THREAD

**Issue by HninPwint** [Jigsaw-Code/outline-client#528]
Hi, 
I got the link error when building the outline-client project in Xcode. The screenshots are the build error and project structure. I am trying to pod files too. However, the error was the same before I used cocapod. 
![screenshot 2019-02-19 at 5 10 26 pm](https://user-images.githubusercontent.com/14988972/53003377-ca321100-3469-11e9-952f-6c9d81bb8482.png)
![screenshot 2019-02-19 at 5 10 48 pm](https://user-images.githubusercontent.com/14988972/53003380-cc946b00-3469-11e9-9344-0792968de46b.png)

**Comment by trevj** [comment]
@HninPwint Thanks for trying Outline. Can you confirm you're using Xcode 10.1?

**Comment by HninPwint** [comment]
Yes, I am using Xcode 10.1.

**Comment by HninPwint** [comment]
Now I am running on the target device, not on Simulator.

**Comment by trevj** [comment]
@HninPwint Thanks for confirming. Turns out our daily builds have been failing. It must be due to our recent migration to Xcode 10.1:
https://github.com/Jigsaw-Code/outline-client/compare/daily-2019-02-10...daily-2019-02-11

@alalamav Do you know what might be happening here? I just tried to build on my laptop here and got the same error.

**Comment by trevj** [comment]
@alalamav First failing build:
https://travis-ci.org/Jigsaw-Code/outline-client/jobs/491903295

**Comment by alalamav** [comment]
Thank you for reporting this. Command line builds are failing due to an incompatibility between cordova-ios < 5.0.0 and Xcode 10. I have addressed this in #530.

I'm not sure that the failure that @HninPwint reported is the same as the one in CI. The error that @HninPwint encountered seems to come from the Xcode project itself, which is not affected by the compatibility issue.

@HninPwint, could please try again after the fix has landed and see if you are able to build the project from Xcode before adding Cocoapods?

**Comment by trevj** [comment]
@alalamav Thanks for the fix. You're right, @HninPwint is seeing a different issue - sorry about that.

@HninPwint I see this error when I try to build for a simulated device or "generic ios device" - but you already said you're building for an actual device? Again, as @alalamav says, please try again with the latest code (`git pull`).

**Comment by HninPwint** [comment]
I have no more build error. I managed to run the outline successfully. Thank you, all. The issue can be closed.

**Comment by trevj** [comment]
@HninPwint Glad to hear it!
