### ISSUE TITLE
the install instruction in outline-client/docs/invitation-instructions.md need update

### ISSUE THREAD

**Issue by yeluolei** [Jigsaw-Code/outline-client#533]
the document is out date for a bit while. for example, the Linux client and Mac Client url is wrong. this link will be send to user every time, it's better to update it to the newest version.

**Comment by trevj** [comment]
@yeluolei Thanks for the report.

@alalamav I had forgotten about this page, do you think it's still valuable given our new support site, etc.?

**Comment by alalamav** [comment]
@trevj, I think so because we link to these from the [Outline manager](https://github.com/Jigsaw-Code/outline-server/blob/95ae9dbe0c6771170789bc16e73f344ce325ee00/src/server_manager/ui_components/outline-share-dialog.html#L116). 

@yeluolei, thanks for the report. I just checked that the macOS client link is correct. As for Linux, the client is still in Beta. We should update the instructions when this is no longer the case.
