### ISSUE TITLE
Problem with iOS when startup

### ISSUE THREAD

**Issue by jackyvictory** [Jigsaw-Code/outline-client#541]
**Describe the bug**
Starting up outline client on my iPhone, only white screen and nothing else, like the screenshot below
![image](https://user-images.githubusercontent.com/15244562/53882346-1330ba80-4051-11e9-8be6-b9c471a22b3d.png)

**To Reproduce**
Simply startup outline client

**Smartphone:**
 - Device: [iPhone6]
 - OS: [iOS9.2.1(13D15)]
 - Outline client version [1.2.6]

Really appreciate anyone's kindly help ~

**Comment by trevj** [comment]
@jackyvictory Thanks for the report.

@alalamav Can you remind what's the earliest supported version of iOS?

**Comment by alalamav** [comment]
@jackyvictory, sorry you're experiencing this issue. Did the iOS client v1.2.5 work for you? 
@trevj, our minimum supported version is 9.0.

I was able to reproduce this issue on iOS 9.3.5. Still looking into the cause, but I have two suspicions for the breakage: upgrading to Xcode 10 and the recent changes to the Gulpfile (transpilation). I'll update this thread once I isolate the root cause.

**Comment by alalamav** [comment]
I have confirmed that this is a transpilation issue related to the refactoring/upgrade of the Gulpfile. I checked out master at bfb9647 (right before #513), compiled with Xcode 10, and the UI is rendered.

**Comment by trevj** [comment]
@alalamav Thanks for tracking down - and apologies for breaking :-/

**Comment by trevj** [comment]
@jackyvictory Thanks again for the report. I hope this is now working for you.
