### ISSUE TITLE
I got 2 errors in xcode when i build the app to iphoneX

### ISSUE THREAD

**Issue by roadhub** [Jigsaw-Code/outline-client#592]
**Describe the issue**
i exec `yarn clean && yarn && yarn gulp build --platform=ios `，It seems to be successful, but I am not sure

![image](https://user-images.githubusercontent.com/18000037/57056576-f2de4e80-6cd5-11e9-89b8-f1c5218ef326.png)

then i open `platforms/ios/Outline.xcworkspace`  in xcode and i switch the toolchains to swift4.2.1 then click then run button

**Environment**
OS: macos mojave 10.14.4
Yarn 1.12.3
Node.js v10.15.0
Xcode version 10.2.1
swift version 4.2.1 -- but when check the version in terminal , it is 5.0.1
![image](https://user-images.githubusercontent.com/18000037/57056711-c414a800-6cd6-11e9-98d1-afca492344cb.png)

**Additional context**
![image](https://user-images.githubusercontent.com/18000037/57056507-9713c580-6cd5-11e9-8ee1-f47c75496c2e.png)

please help me

**Comment by alalamav** [comment]
@roadhub, I think there are two issues here. The first is that you are building for the simulator (x86_64 architecture), which is not supported since the NetworkExtension framework is not available. 

The second is that we haven't yet migrated to Xcode 10.2 (Swift 5) -  see #563. I think changing the toolchain should work as a workaround for now.
