### ISSUE TITLE
I install OpenVPN. I can't install outline client after uninstalling OpenVPN

### ISSUE THREAD

**Issue by net-alan** [Jigsaw-Code/outline-client#740]
Sorry we could not configure your system to connect to Outline. Please try running the installer again. if you still cannot install outline. please get in touch with us and let us know that the TAP device could not be installed.

**Comment by net-alan** [comment]
Windows 10 system, what should I do

**Comment by alalamav** [comment]
HI @net-alan, Outline and OpenVPN share the network adapter source code, which is why uninstalling OpenVPN deleted it. I suggest you uninstall Outline and re-install it. If you run into install issues, please install [v1.2.34](https://github.com/Jigsaw-Code/outline-client/releases/windows-v1.2.34).

Feel free to reopen this issue if the problem persists.
