### ISSUE TITLE
Development and changes

### ISSUE THREAD

**Issue by MWalid** [Jigsaw-Code/outline-client#749]
Hello,

Is it required every time a change is made to the UI to run:
```
yarn gulp build --platform=browser
yarn cordova run browser
```
Which takes more than 20 seconds. Any other way to see changes in development mode without needing to rebuild the whole thing?

**Comment by alalamav** [comment]
@MWalid, for UI development, you can avoid running the entire build by editing the files in `platforms/browser/www/ui_components/`. Changes would be available on page reload. Make sure to copy any changes back to `src/www`; otherwise they would be overwitten the next time you build.

Feel free to reopen this issue if you have further questions.

**Comment by JonathanDCohen** [comment]
@alalamav I had tried to work out using the "watch" mode of `tsc` and options for hot reload in electron a little while ago.  It might be worthwhile to look back into incremental rebuild options.

**Comment by JonathanDCohen** [comment]
@MWalid depending on what you're doing you may also want to try `yarn do src/electron/run` if running the electron version of the app will work for you.

**Comment by MWalid** [comment]
Thank you guys for the response, 

@alalamav I believe this is a good option, it could be more helpful if combined with a gulp task that does the watch and copy on change.

@JonathanDCohen we are focused on Cordova rather than electron for now, is there anything like `yarn do src/cordova/run` ?
