### ISSUE TITLE
Is Outline abandoned (dead)?

### ISSUE THREAD

**Issue by lgg** [Jigsaw-Code/outline-client#776]
It's look like project isn't actively maintained since spring 2019. There are bunch of issues and unresolved useful merge requests. Main maintainers don't work on this project.
It seems like only @alalamav fixing some issues from time to time (thank you for that!!!)

Outline Client:
![image](https://user-images.githubusercontent.com/12018713/79141865-4b154000-7dc3-11ea-8ac8-4a629d14c9ba.png)

Outline server:
![image](https://user-images.githubusercontent.com/12018713/79141906-58cac580-7dc3-11ea-97d3-8ac42e730b97.png)

---

@fortuna @trevj @alalamav @JonathanDCohen please, answer - what is the future of the Outline?
What is happening to Outline right now?

Thank you for your work and great project! ❤️

**Comment by JonathanDCohen** [comment]
Outline is very much alive, we've just been focusing much more on the server.  We are currently even onboarding a new engineer!  What did happen there in early 2019 is that @trevj left the team and I joined and had to start onboarding, which left a large knowledge vacuum.

**Comment by fortuna** [comment]
There has been a constant flow of changes to Outline, in this repository and the other ones. Some things we did since spring 2019:
- Added support for multiple servers
- Re-wrote the Shadowsocks server in Go ([outline-ss-server](https://github.com/Jigsaw-Code/outline-ss-server)), becoming the safest Shadowsocks server out there, with feature others don't support, such as multiple users on a single port and private metrics
- Added new protection against probing attacks, which got servers unblocked in Iran
- Added data limits
- Added option to change the port number and hostname for keys
- We're experimenting with protection against replay attacks.

Here are some of the announcements: https://www.reddit.com/r/outlinevpn/?f=flair_name%3A%22Announcement%22

Our team lost a few engineers, but we've re-staffed the team recently.

**Comment by alalamav** [comment]
Outline is indeed alive! 

Regarding work on the clients, I would add that last year we focused on migrating the clients' network stack to Go from `shadowsocks-libev` and `badvpn-tun2socks`. You can follow the progress in [ outline-go-tun2socks](https://github.com/Jigsaw-Code/outline-go-tun2socks/) and  [alalama-go-tun2socks](https://github.com/Jigsaw-Code/outline-client/tree/alalama-go-tun2socks). 

The Go network stack has been rolled to production for iOS and macOS, and is being beta-tested in other platforms. Those contributions are not in `master` yet, so I'm not sure if they appear on the repo contibutions graph.

**Comment by lgg** [comment]
Thank you very much! I'm glad to hear that.

**Comment by xmha97** [comment]
@JonathanDCohen Why don't you update Outline?
The outline has many problems :(
https://github.com/Jigsaw-Code/outline-client/issues/781
