### ISSUE TITLE
Outline-Client does not install on windows 10 

### ISSUE THREAD

**Issue by ahmed9560** [Jigsaw-Code/outline-client#791]
hello i have a promlem
![2](https://user-images.githubusercontent.com/65418174/82087235-6217bc80-96f8-11ea-95bf-8ed4e39b4c5b.png)
![erorr](https://user-images.githubusercontent.com/65418174/82087237-6348e980-96f8-11ea-86bf-80bb751653bf.png)

Outline-Client does not install on windows 10 give me  Messages 

 - OS: windows 10
 - chrome
 - 1.3.3

**Comment by iamsid47** [comment]
You can do two things here:

1. Uninstall just everything regarding Outline. Whether it be it's files, cache, and also if it has a folder in the system registry. After that, clean install the Outline Client/Manager and see if the issue persist.
2. If it does, you can check out your antivirus settings or your firewall settings. Many times it happens that applications are not allowed to be installed on some devices due to it's antivirus system. So, that can be a considerable point.

**Comment by ahmed9560** [comment]
It worked . I cleaned everything, closed the anti-virus and firewall and installed it . Thank you very much .

**Comment by alalamav** [comment]
Glad this worked for you @ahmed9560. Thanks @iamsid47 for the workaround.
