### ISSUE TITLE
Issue While Building App !! How to setup local build and test the application for ios

### ISSUE THREAD

**Issue by PR4SAN** [Jigsaw-Code/outline-client#844]
**Describe the issue**
A clear and concise description of what the issue is. If possible, paste the output from your terminal.

Followed the steps but when generating local test build I am getting the following console error.

`=== BUILD TARGET VpnExtension OF PROJECT Outline WITH CONFIGURATION Debug ===

Check dependencies
Code Signing Error: No profiles for 'org.outline.ios.client.VpnExtension' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'org.outline.ios.client.VpnExtension'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
Code Signing Error: Code signing is required for product type 'App Extension' in SDK 'iOS 13.6'

** ARCHIVE FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
xcodebuild: Command failed with exit code 65
[20:26:57] 'cordovaCompile' errored after 16 s
[20:26:57] Error: exited with error code: 65
    at ChildProcess.onexit (/Users/suprasanna/Documents/outline-client/node_modules/end-of-stream/index.js:39:36)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:506:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at Process.callbackTrampoline (internal/async_hooks.js:120:14)
[20:26:57] 'build' errored after 3.97 min
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Environment**
   iOS
 - Yarn version
    1.22.4
 - Node.js version
   v12.18.3
**Additional context**

**Comment by alalamav** [comment]
@PR4SAN, it seems like you were able to create the Xcode project. Right now it fails to compile because don't have access to the certificates and provisioning profiles of `org.outline.ios.client`. I suggest you open the project at `outline-client/platforms/ios/Outline.xcodeproj` with Xcode and change the identifiers to your own IDs for the Outline and VpnExtension targets. Xcode should be able to provision the entitlements and sign the app automatically.

You may need to have a Apple Developer Program membership to deploy to a device (the simulator is not supported).

Feel free to re-open this issue if you have more questions.
