### ISSUE TITLE
Restore Outline window from system tray on Linux

### ISSUE THREAD

**Issue by pk-r** [Jigsaw-Code/outline-client#860]
Hello Guys

I'm having trouble with restoring outline window once i have minimized it. I expect to be able to to do this by clicking on system
tray or by using system tray menu to restore it, but what I get is just a menu that only includes a status and quit button.
It happens with both mouse clicks (right and left). I have to launch the program again to restore window.

Steps to reproduce the behavior (Linux x64):
1. Open Outline
2. Minimize or exit the window
3. Click the system tray for showing the window again
4. See there is no way to restore the outline window 

I expect to:
Be able to restore the window just by clicking the tray, or selecting it on tray menu.

System:
Kubuntu 20.04

Thank you

**Comment by thiras** [comment]
I confirm the bug on the latest Ubuntu 20.04. Very annoying bug.

**Comment by aps2201** [comment]
OpenSUSE Leap 15.2 also confirmed issue. Very annoying when wanting to change servers. The only way to restore the window is by running the appimage again.

**Comment by fortuna** [comment]
Thanks for the report. I'm sorry for the trouble.
I have a fix to allow you to minimize the window: https://github.com/Jigsaw-Code/outline-client/pull/971

The tray is not triggering the window because of this Electron bug: https://github.com/electron/electron/issues/14941
We need to add a "Open Window" menu entry to the tray as a workaround.
