### ISSUE TITLE
Cannot connect to server on Mac

### ISSUE THREAD

**Issue by canaokar** [Jigsaw-Code/outline-client#884]
I downloaded the latest Outline version and created the server using AWS. I am able to connect on my phone and Windows machine but Mac app doesn't seem to respond. The error I am getting is:

> Sorry, an unexpected error occurred. Quitting and restarting might help. If this happens again, please submit feedback. 

I have tried reinstalling the app, I have also tried rebooting the system. Has anyone got similar problems?

**Comment by ruslaniv** [comment]
Yes, this is still the issue! I'm getting this on OSX version 1.9.0

**Comment by Polyuretan** [comment]
I fixed it on my MacOS simply. Open MacOS Settings - click in network button - then VPN - then click on the info icon (button) and click delete configuration. After just relaunch Outline Client and it will ask you to allow add new configuration. 
And after just connect to your server. It works for me.

**Comment by avgilderman** [comment]
> 

It works for me! I had to repeat this method several times, and I also deleted the my vpn from outline app every time. 
Thank you!

**Comment by rohanmehra20** [comment]
Thank you for reaching out! If this is still an issue for you, please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
